var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/chat/page.js")
R.c("server/chunks/ssr/_4f048b94._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5680740e._.js")
R.c("server/chunks/ssr/_94a6030d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__b633ec40._.js")
R.c("server/chunks/ssr/a5ed4_next_dist_3589e963._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9dc7016d._.js")
R.c("server/chunks/ssr/a5ed4_next_dist_client_components_builtin_global-error_9a0e1fbe.js")
R.c("server/chunks/ssr/src_app_layout_tsx_cc8184fa._.js")
R.c("server/chunks/ssr/src_app_not-found_tsx_0f6131ce._.js")
R.c("server/chunks/ssr/a5ed4_next_dist_client_components_798f34d2._.js")
R.c("server/chunks/ssr/a5ed4_next_dist_client_components_builtin_unauthorized_796277bf.js")
R.c("server/chunks/ssr/_next-internal_server_app_chat_page_actions_c92d15a6.js")
R.m(78936)
module.exports=R.m(78936).exports
