var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/_430ced8f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5680740e._.js")
R.c("server/chunks/ssr/a5ed4_next_dist_esm_build_templates_app-page_cfe9e354.js")
R.c("server/chunks/ssr/[root-of-the-server]__1c900af5._.js")
R.c("server/chunks/ssr/a5ed4_next_dist_3589e963._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9dc7016d._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_cc8184fa._.js")
R.c("server/chunks/ssr/src_app_not-found_tsx_0f6131ce._.js")
R.c("server/chunks/ssr/a5ed4_next_dist_client_components_798f34d2._.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_554ec2bf.js")
R.m(28162)
module.exports=R.m(28162).exports
